drop table if exists monsterDef;
create table monsterDef (
	id int primary key not null auto_increment,
	sname varchar(16) unique,
	index(sname),
	lname varchar(32),
	level int,
	baseaffinity varchar(4),
	basetype varchar(32),
	baseelement varchar(4),
	reqhealth int,
	reqstamina int,
	reqmana int,
	reqspeed int,
	reqstrength int,
	reqdexterity int,
	reqfocus int,
	reqresolve int,
	basehealth int,
	basestamina int,
	basemana int,
	basestrength int,
	basedexterity int,
	basefocus int,
	baseresolve int,
	reqmaterial int,
	reqether int,
	reqspirit int,
	reqabyss int,
	reqwins int,
	reqlosses int,
	special varchar(16),
	skills varchar(512),
	requirements varchar(255)
);
