drop table if exists monsterData;
create table monsterData(
	id int primary key not null auto_increment,
	playerId int not null,
	index (id,playerId),
	monsterId int not null,
	level int,
	birthdate int,
	material float(7,4),
	ethereal float(7,4),
	spiritual float(7,4),
	abyssal float(7,4),
	health float(7,4),
	stamina float(7,4),
	mana float(7,4),
	fatigue float(7,4),
	basehealth float(7,4),
	basestamina float(7,4),
	basemana float(7,4),
	basespeed float(7,4),
	basefatigue int,
	strength int,
	strengthtrain int,
	dexterity int,
	dexteritytrain int,
	focus int,
	focustrain int,
	resolve int,
	resolvetrain int,
	wins int,
	losses int,
	draws int,
	special varchar(32),
	move1 varchar(32),
	move2 varchar(32),
	move3 varchar(32),
	move4 varchar(32),
	move5 varchar(32),
	move6 varchar(32),
	move7 varchar(32),
	location varchar(32),
	activity varchar(32)
);
